# Generated by Django 2.2.2 on 2019-06-26 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0002_auto_20190624_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='part_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department74.Part'),
        ),
    ]
