# Generated by Django 2.2.2 on 2019-06-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0003_components_part_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='components',
        ),
        migrations.AddField(
            model_name='components',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department74.Computer'),
        ),
    ]
