# Generated by Django 2.2.2 on 2019-06-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0005_computer_type_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department74.Computer'),
        ),
        migrations.AlterField(
            model_name='components',
            name='part_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department74.Part'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type_components',
            field=models.ManyToManyField(blank=True, to='department74.TypeComponents'),
        ),
    ]
