# Generated by Django 2.2.2 on 2019-07-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0008_computeritems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='computeritems',
            name='computer_id',
        ),
        migrations.RemoveField(
            model_name='computeritems',
            name='type_components',
        ),
        migrations.RemoveField(
            model_name='computeritems',
            name='type_components_quantity',
        ),
        migrations.AddField(
            model_name='computeritems',
            name='computer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='department74.Computer'),
        ),
        migrations.AddField(
            model_name='computeritems',
            name='item',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='department74.TypeComponents'),
        ),
        migrations.AddField(
            model_name='computeritems',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='type_components',
            field=models.ManyToManyField(through='department74.ComputerItems', to='department74.TypeComponents'),
        ),
    ]
