# Generated by Django 2.2.2 on 2019-07-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0009_auto_20190701_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeritems',
            name='computer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='department74.Computer'),
        ),
    ]
