# Generated by Django 2.2.2 on 2019-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0013_auto_20190701_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='type_components',
            field=models.ManyToManyField(through='department74.ComputerItems', to='department74.TypeComponents'),
        ),
    ]
