# Generated by Django 2.2.2 on 2019-07-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0014_auto_20190701_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computeritems',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='computeritems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='components',
            name='computer',
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
        migrations.DeleteModel(
            name='ComputerItems',
        ),
    ]
