# Generated by Django 2.2.2 on 2019-07-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0015_auto_20190701_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CompItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department74.Comp')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department74.TypeComponents')),
            ],
        ),
        migrations.AddField(
            model_name='comp',
            name='ingredients',
            field=models.ManyToManyField(through='department74.CompItems', to='department74.TypeComponents'),
        ),
    ]
