# Generated by Django 2.2.2 on 2019-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0016_auto_20190701_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='serial_number',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
