# Generated by Django 2.2.2 on 2019-07-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0017_comp_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comp',
            old_name='ingredients',
            new_name='items',
        ),
    ]
