# Generated by Django 2.2.2 on 2019-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0018_auto_20190701_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compitems',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
