# Generated by Django 2.2.2 on 2019-07-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0019_auto_20190701_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department74.Part'),
        ),
    ]
