# Generated by Django 2.2.2 on 2019-07-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0020_comp_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='serial_number',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='compitems',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department74.Comp', verbose_name='Серийный номер машины'),
        ),
        migrations.AlterField(
            model_name='compitems',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department74.TypeComponents', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='compitems',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
