# Generated by Django 2.2.2 on 2019-07-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0021_auto_20190703_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compitems',
            name='quantity',
        ),
    ]
