# Generated by Django 2.2.2 on 2019-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0022_remove_compitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='compitems',
            name='quantity',
            field=models.ManyToManyField(to='department74.Quantity'),
        ),
    ]
