# Generated by Django 2.2.2 on 2019-07-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0023_auto_20190703_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compitems',
            name='quantity',
        ),
        migrations.AddField(
            model_name='compitems',
            name='quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department74.Quantity'),
        ),
    ]
