# Generated by Django 2.2.2 on 2019-07-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0024_auto_20190703_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='part_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department74.Part'),
        ),
    ]
