# Generated by Django 2.2.2 on 2019-07-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0026_auto_20190704_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compitems',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='comp',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='department74.CompItems'),
        ),
        migrations.AlterField(
            model_name='compitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
