# Generated by Django 2.2.2 on 2019-07-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0027_auto_20190704_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compitems',
            old_name='item',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='items',
        ),
        migrations.AddField(
            model_name='comp',
            name='items',
            field=models.ManyToManyField(through='department74.CompItems', to='department74.TypeComponents'),
        ),
        migrations.AlterField(
            model_name='compitems',
            name='quantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department74.Quantity'),
        ),
    ]
