# Generated by Django 2.2.3 on 2019-07-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department74', '0030_auto_20190716_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
